name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' or your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # assumes your HTML is in the root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
